name: Maven build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'modules/**'
      - 'features/**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Call Build Workflow
    uses: doytowin/doyto-devops/.github/workflows/build.yml@main
    secrets: inherit
    with:
      java-version: 17
      sonar-project-name: 'doyto-query'
      sonar-project-key: 'win.doyto:doyto-query'
